### ISSUE TITLE
Scrutiny plugin shows no data on web UI

### ISSUE THREAD

**Issue by kajmaj** [OpenMediaVault-Plugin-Developers/packages#11]
I run OMV 6.1.3-1 (Shaitan) on RPi 4. 
I have installed Scrutiny via compose file scrutiny.yml >> image [ghcr.io/analogj/scrutiny:master-omnibus](http://192.168.1.121:9000/#!/2/docker/images/ghcr.io~2Fanalogj~2Fscrutiny%3Amaster-omnibus) 
In portainer ic scrutiny container shown as running
![scrutiny_portainer](https://user-images.githubusercontent.com/37018655/210087659-71b52256-98c7-48a8-bb04-de2669057342.png)

But web UI shows no info about installed HDDs/SSDs 
![Scrutiny Dashboard](https://user-images.githubusercontent.com/37018655/210087789-7eaa02c0-1995-4e7f-9c02-e7f53ba72c75.png)

If I try to open InfluxDb, it shows login page, but as it is requiring username/password I do not know, I cannot login as well.

`ctrl+shift+R` does not help, tried Opera, Chrome, Edge.
OMV reboot does not help as well

Did I omit anything? Any advice pls?

**Comment by ryecoaaron** [comment]
Please post on the [forum](https://forum.openmediavault.org/).  I didn't write that compose file and don't use Scrutiny.  You will get better support on the forum.
