### ISSUE TITLE
Unsupported version of openmediavault

### ISSUE THREAD

**Issue by xiaokangit** [OpenMediaVault-Plugin-Developers/packages#12]
dpkg-query: no packages found matching openmediavault
0
Unsupported version of openmediavault

**Comment by ryecoaaron** [comment]
Not sure what you have done to get to this point.  Can you please post on the forum?  https://forum.openmediavault.org/

**Comment by xiaokangit** [comment]
> Not sure what you have done to get to this point. Can you please post on the forum? https://forum.openmediavault.org/

![Snipaste_2023-03-20_20-14-57](https://user-images.githubusercontent.com/77732275/226336691-6d1e91a0-d484-4ef8-9d9a-04f5cb8f087d.png)

**Comment by ryecoaaron** [comment]
The install script in this repo ONLY installs omv-extras.  Please look at https://github.com/OpenMediaVault-Plugin-Developers/installScript and follow the guide - https://forum.openmediavault.org/index.php?thread/28789-installing-omv6-or-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/

**Comment by xiaokangit** [comment]
> 此存储库中的安装脚本仅安装 omv-extras。请查看 https://github.com/OpenMediaVault-Plugin-Developers/installScript 并遵循指南 - https://forum.openmediavault.org/index.php?thread/28789-installing-omv6-or-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/



> 此存储库中的安装脚本仅安装 omv-extras。请查看 https://github.com/OpenMediaVault-Plugin-Developers/installScript 并遵循指南 - https://forum.openmediavault.org/index.php?thread/28789-installing-omv6-or-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/

I executed this script to this step and reported an error
![Snipaste_2023-03-20_20-46-24](https://user-images.githubusercontent.com/77732275/226342888-15ef304e-2a90-4256-b2b3-d1bf6265bf30.png)

**Comment by ryecoaaron** [comment]
> I executed this script to this step and reported an error

That script is not part of omv-extras.  The install script I linked to works better in my opinion.  But either way, the install script in this repo is not responsible for install openmediavault just omv-extras.  Please post on the forum for more help.

**Comment by xiaokangit** [comment]
> > I executed this script to this step and reported an error
> 
> That script is not part of omv-extras. The install script I linked to works better in my opinion. But either way, the install script in this repo is not responsible for install openmediavault just omv-extras. Please post on the forum for more help.

ok, thanks for replying
