### ISSUE TITLE
Why using this crooked wget|bash approach?

### ISSUE THREAD

**Issue by amie42** [OpenMediaVault-Plugin-Developers/packages#13]
Hi folks, 

thanks a mill for supporting that really nice project. 
I do have an issue with your deployment approach though. I mean you do rely on Debian for entirely. Debian  has a great packet manager, apt, which you are already using by providing .deb packages. Is there any reason why you are not using that packet manager entirely by simply providing a packet repository that follows the Debian specs instead of this wget|bash 💩? I mean it wouldn't be _THAT_ hard, right? And you would gain a lot like versioning and stuff.

Sorry for that rant by an old mumbling man

Amie

**Comment by ryecoaaron** [comment]
Please read what the script is doing. It is just making sure to install the package dependencies from the Debian package repo and then install the proper version of the omv-extras debian package. Versioning is already being extensively used in standard debian way.
