### ISSUE TITLE
Installation did not work in version 7

### ISSUE THREAD

**Issue by Keeyuu** [OpenMediaVault-Plugin-Developers/packages#21]
I used the latest version 7, then installed it using the installation script in the repository, and everything worked fine, no error,then I also restarted the machine, but the extra plug-ins did not show up in the web

**Comment by ryecoaaron** [comment]
Do you have output from the script?  Did you hit ctrl-shift-R to refresh the browser cache?  What is the output from:  dpkg -l | grep openme

**Comment by Keeyuu** [comment]
> Do you have output from the script? Did you hit ctrl-shift-R to refresh the browser cache? What is the output from: dpkg -l | grep openme

ctrl-shift-R after refreshing the browser, nothing has changed. Using dpkg -l | grep openme is also very strange  
ii  openmediavault                  7.0.4-2                              all          openmediavault - The open network attached storage solution
ii  openmediavault-keyring          1.0.2-2                              all          GnuPG archive keys of the openmediavault archive
ii  openmediavault-podman           7.0-3                                all          openmediavault Podman plugin
ii  openmediavault-sharerootfs      7.0-1                                all          openmediavault share root filesystem plugin

**Comment by ryecoaaron** [comment]
omv-extras isn't installed at all.  Can you run the install script again and post the output?

**Comment by Keeyuu** [comment]
> omv-extras isn't installed at all. Can you run the install script again and post the output?

Remarkably, I attempted the installation process once more, and to my profound gratitude, it succeeded.

**Comment by BoOmka** [comment]
For anyone looking for a solution, I had the same problem when I tried to start with
```bash
su root
```

instead of what mentioned in README.md: 
```
su -
```
