### ISSUE TITLE
after remove

### ISSUE THREAD

**Issue by Florock** [OpenMediaVault-Plugin-Developers/packages#3]
Hello,
after I installed the plugin the entry in System->ovm-extra is still there. I have OMV6

**Comment by ryecoaaron** [comment]
This really belongs here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues

Fixed here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/a9ae1bfd14010f2e83ff9be23f2abf46c05132ae  I will release after I make some other changes.

Why are you removing it?

**Comment by ryecoaaron** [comment]
To fix, just run:  sudo omv-mkworkbench all
