### ISSUE TITLE
Enable armel architecture

### ISSUE THREAD

**Issue by dotted** [OpenMediaVault-Plugin-Developers/packages#6]
I am currently running OMV6 on Bullseye on a QNAP TS-221 NAS, but when installing OMV-Extra I am not getting any new plugins to install as the repo doesn't list armel as a supported architecture, it would be nice if armel could be enabled as plenty of packages in the repo are listed as architecture independent and should install just fine on armel.

**Comment by ryecoaaron** [comment]
I dropped support for armel early in the OMV 3.x days because it is painfully slow and I don't have an armel system I want to test on.  And while most would probably work, the package's architecture being architecture independent doesn't necessarily mean it will work.  So, I would prefer not to support armel.

**Comment by Forage** [comment]
It would be good to state this in the documentation somewhere to avoid people going through the trouble of installing the OMV Extra plugin...only to find that not a single additional plugin is available for this platform.

**Comment by ryecoaaron** [comment]
As I mentioned above, many of the plugins will work.  There just is no repo.  armel hasn't been available in omv-extras for almost 10 years.  Strange that I would have to mention it isn't available now.

All of the omv-extras documentation mentions using the install script.  The install script will tell you armel isn't supported.

I will find somewhere to mention it other than the forum and the install script.

**Comment by Forage** [comment]
I ran into it now despite the 10 years ;-)

The script installed just fine, the extra addon was present in the UI afterwards and all. It would be good to adapt the script to not install the extra addon package at all if it won't provide any additional plugins.

At least https://wiki.omv-extras.org/doku.php?id=misc_docs:omv_extras would be a suitable place to mention it I suppose.

**Comment by ryecoaaron** [comment]
> The script installed just fine, the extra addon was present in the UI afterwards and all. It would be good to adapt the script to not install the extra addon package at all if it won't provide any additional plugins.

As I mentioned, it already is - https://github.com/OpenMediaVault-Plugin-Developers/installScript/blob/master/install#L202

Your board must not be returning armel from the arch command if the install script worked.  Either that or you are referring to the omv-extras install script which typically isn't run on arm boards because the full install script is run.  I will add the check to omv-extras.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/packages/commit/b86d399587536398673aa54823d797bb32fd0f42

**Comment by ryecoaaron** [comment]
The summary on the page you linked to also says it only applies to amd64 installations.

**Comment by Forage** [comment]
I read that statement as only related to when it is installed by default. I figured since I performed a manual OMV installation, it doesn't apply to me and I have to install the add-on manually as well. I did not see it as related to what is actually supported.

**Comment by flmaxey** [comment]
> **_I figured since I performed a manual OMV installation, it doesn't apply to me and I have to install the add-on manually as well. I did not see it as related to what is actually supported in terms of platforms._**

Well, without consulting documentation, sometimes when we make assumptions they're actually mistakes.  After reading this thread; I added an additional note in the OMV-Extras doc, to specifically state that ARMEL platforms are not supported (even if manually installed).

[https://wiki.omv-extras.org/doku.php?id=misc_docs:omv_extras#summary](url)

**Comment by Forage** [comment]
But I did consult the docs, hence me referring to that page. Nowhere else is explicitly stated which platforms are supported and I had no reason to assume it wasn't the case for mine. That one line only referred to installation, not support. That it has been written with a different intent indicates that its meaning is ambiguous.

Now that ARMEL is specifically mentioned, there won't be any confusion any more for at least that platform. Thanks.
