### ISSUE TITLE
delete? 

### ISSUE THREAD

**Issue by Tajemniaczek** [OpenMediaVault-Plugin-Developers/packages#9]
https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master delete github? :(

**Comment by ryecoaaron** [comment]
I’m not sure what you are asking?

**Comment by Tajemniaczek** [comment]
I am asking because it does not work? For 3 hours the repository is unavailable, if not longer. Please check. The installation does not work.

**Comment by Tajemniaczek** [comment]
![image](https://user-images.githubusercontent.com/52765147/179370403-f417c8df-e4a8-45a4-8198-81006decb620.png)

**Comment by ryecoaaron** [comment]
I can’t read that but I’m guessing either you don’t have dns working properly or your network is blocking github. If github is down, there is nothing I can do about that.

**Comment by Tajemniaczek** [comment]
I have nothing. I am active, I can see all the things available. Like github etc. Browse raw file I can see the file from github which is locked. His relationship. https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/ I just wanted to reinstall the add-on and that's it. And nothing works. Have you checked at home or are you just writing that it works?

**Comment by Tajemniaczek** [comment]
i try repair

**Comment by ryecoaaron** [comment]
> Have you checked at home or are you just writing that it works?

Nope because I am not home because I am on vacation.  I am writing that it should work since github is up.  I know github is up because we are posting on this issue.  I just logged into one of my systems at home and the repo is working just fine.  So, this must be something on your end.  I do not know what.
